Document: robotkernel-service-helper
Title: Debian robotkernel-service-helper Manual
Author: <insert document author here>
Abstract: This manual describes what robotkernel-service-helper is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/robotkernel-service-helper/robotkernel-service-helper.sgml.gz

Format: postscript
Files: /usr/share/doc/robotkernel-service-helper/robotkernel-service-helper.ps.gz

Format: text
Files: /usr/share/doc/robotkernel-service-helper/robotkernel-service-helper.text.gz

Format: HTML
Index: /usr/share/doc/robotkernel-service-helper/html/index.html
Files: /usr/share/doc/robotkernel-service-helper/html/*.html
