Document: robotkernel-generator
Title: Debian robotkernel-generator Manual
Author: <insert document author here>
Abstract: This manual describes what robotkernel-generator is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/robotkernel-generator/robotkernel-generator.sgml.gz

Format: postscript
Files: /usr/share/doc/robotkernel-generator/robotkernel-generator.ps.gz

Format: text
Files: /usr/share/doc/robotkernel-generator/robotkernel-generator.text.gz

Format: HTML
Index: /usr/share/doc/robotkernel-generator/html/index.html
Files: /usr/share/doc/robotkernel-generator/html/*.html
