name: Makefile CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ bookworm, bullseye ]
    container:
      image: debian:${{ matrix.distro }}
    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: apt-get update && apt-get install -y build-essential autoconf automake libtool git

      - name: update branch name
        run: |
          safe_branch="${GITHUB_REF_NAME//\//-}"
          sed "s|BRANCH_VERSION|$safe_branch|" configure.ac.in > configure.ac
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          
      - name: autoreconf
        run: autoreconf -i -f
      
      - name: configure
        run: ./configure

      - name: Install dependencies
        run: make

      - name: Run check
        run: make check

      - name: Run distcheck
        run: make distcheck

      - name: Upload source tarball
        uses: actions/upload-artifact@v4
        with:
          name: autotools-dist
          path: ./*.tar.gz
